# Generated by Django 5.0.2 on 2024-02-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mybooks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Books",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=200, null=True)),
                ("image", models.ImageField(null=True, upload_to="photos")),
                ("review", models.TextField(max_length=1000, null=True)),
            ],
        ),
    ]
