# Generated by Django 5.0.2 on 2024-02-28 06:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mybooks", "0003_like"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="like",
            new_name="liked",
        ),
    ]
