# Generated by Django 5.0.2 on 2024-02-28 06:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mybooks", "0004_rename_like_liked"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="liked",
            name="customer",
        ),
    ]
